networks:
  default:
    name: '${DOCKER_NAME}-network'
    driver: bridge

services:
  app:
    container_name: '${DOCKER_NAME}-app'
    build:
      context: ./
      dockerfile: docker/dockerfile
      args:
        WWWGROUP: '${DOCKER_GID}'
        TIMEZONE: '${DOCKER_TIMEZONE}'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
        WWWUSER: '${DOCKER_UID}'
        IGNITION_LOCAL_SITES_PATH: '${PWD}'
        APP_HOST_PORT: '${APP_HOST_PORT}'
    ports:
      - '${APP_HOST_PORT}:80'
    volumes:
      - ./:/app/:cached
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/templates/nginx.conf
      - ./docker/dev/nginx/html:/etc/nginx/html
      - ./docker/dev/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - default
