networks:
  default:
    name: '${DOCKER_NAME}-network-prod'
    driver: bridge

services:
  app-prod:
    container_name: '${DOCKER_NAME}-app-prod'
    build:
      context: ./
      dockerfile: docker/dockerfile
      args:
        WWWGROUP: '${DOCKER_GID}'
        TIMEZONE: '${DOCKER_TIMEZONE}'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
        WWWUSER: '${DOCKER_UID}'
        IGNITION_LOCAL_SITES_PATH: '${PWD}'
    ports:
      - '${APP_HOST_PORT}:80'
    volumes:
      - ./:/app
      - ./docker/prod/nginx/nginx.conf:/etc/nginx/sites-available/default
      - ./docker/prod/nginx/html:/etc/nginx/html
      - ./docker/prod/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - default
